import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Provider } from "@/components/ui/provider";

export const metadata: Metadata = {
  title: "Shopping Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <React.StrictMode>
          <Provider defaultTheme="light">{children}</Provider>
        </React.StrictMode>
      </body>
    </html>
  );
}
